### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by tramidev** [letharqic/InstantPipes#2]
Projects with Instapipe can't be build, some editor scripts are added to build process.
Editor scripts are well placed on Editor folder but the leth.instantpipes.Editor.asmdef are targeted for all platforms.

**Comment by leth4** [comment]
Hello! Have you updated the package / downloaded the latest version? I'm fairly sure this was fixed a few commits ago.

**Comment by tramidev** [comment]
Hi! I can't see the change needed to work on the latest code
On Let.instantpipes.Editor.asmdef includePlatform need to have "Editor", this exclude all other platforms
`{
    "name": "leth.instantpipes.Editor",
    "rootNamespace": "InstantPipes",
    "references": [],
    "includePlatforms": ["Editor"],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}`

**Comment by leth4** [comment]
If I do that, I can't attach the pipe component to the objects anymore, can I? I wrapped the editor code in `#if UNITY_EDITOR` instead, which is a lazy solution but (supposedly) works fine.

**Comment by leth4** [comment]
I also tried to make a separate asmdef for the runtime stuff, but then the editor script fails to see the pipe script. There's probably a proper solution with proper assembly definitions somewhere there, but I haven't figured it out.

**Comment by tramidev** [comment]
You have right! I was severing all the references haha
Let me do a proper pull request to fix it on the night

**Comment by leth4** [comment]
Just discovered assembly definition references, took me a while lol. I'll push a proper fix in a few minutes.
