### ISSUE TITLE
Suggestion: change material for curved parts

### ISSUE THREAD

**Issue by ratkingsminion** [letharqic/InstantPipes#4]
This is a great tool! I just wondered how hard it would be to implement a material change for curved elements. An idea would be that they'd have the same material as the rings.

Maybe it'd even be possible to change the curved elements' radius a bit?

**Comment by leth4** [comment]
Hi! Went ahead and added it; toggle the `Extrusion` under the `Rings` toggle to use it, the radius property is shared with rings. Please note that using curved elements basically doubles the vertex count of a pipe. Also, those won't look very good in parts where your curvature is longer then the pipe segment, so you'll probably want to keep the curvature low and even manually edit the last segment, as it tends to be very short. 

Please let me now if you encounter any problems.

**Comment by ratkingsminion** [comment]
That's really great, thanks a lot!

As for the doubled vertex count, would it be possible to just omit the vertices for the curvature underneath the extruded rings? (I guess it's not that easy.)

**Comment by leth4** [comment]
Turned out to be an actual one-line fix lol. No extra vertices now!

**Comment by ratkingsminion** [comment]
Awesome! Thanks for the quick replies and changes. Really didn't expect that =)

**Comment by leth4** [comment]
You're welcome! Happy to help C:
