### ISSUE TITLE
Moving camera changes point selection

### ISSUE THREAD

**Issue by ratkingsminion** [letharqic/InstantPipes#5]
When editing a pipe by moving the points around I often encounter this problem: I have one or more points selected, move the camera around (via RMB and WASD) and when I try to move the selected point(s) again, all of them (the whole pipe) gets moved instead, because the selection was changed to all points of the pipe.

Update: I think it's because "A" selects all points...

**Comment by leth4** [comment]
Good catch, thanks. Fixed in the latest commit!
